baseURL = 'https://zombieapocalypsetech.com/'
languageCode = 'en-us'
title = 'Zombie Apocalypse Tech'
titleAbbrv = 'ZAT'
theme = 'zat'
summaryLength = 40

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
